version: '3.9'

services:
  app:
    build: .
    container_name: soporte_app
    ports:
      - "8080:80"
    environment:
      # Defaults si no existen en .env
      - APP_ENV=${APP_ENV:-local}
      - APP_DEBUG=${APP_DEBUG:-true}
      - APP_URL=${APP_URL:-http://localhost:8080}
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE:-tickets}
      - DB_USERNAME=${DB_USERNAME:-tickets}
      - DB_PASSWORD=${DB_PASSWORD:-secret}
    volumes:
      - ./:/var/www/html:Z
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: soporte_db
    command: --default-authentication-plugin=mysql_native_password --sql-mode="" --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - MYSQL_DATABASE=${DB_DATABASE:-tickets}
      - MYSQL_USER=${DB_USERNAME:-tickets}
      - MYSQL_PASSWORD=${DB_PASSWORD:-secret}
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p$$MYSQL_ROOT_PASSWORD || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
    ports:
      - "33060:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
